name: apple
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/salahu01/apple

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
# Add regular dependencies here.
dependencies:
  http: ^0.13.4
  process_run: ^0.12.0
  mason_logger: ^0.1.0+1
  console_bars: ^1.2.0
  logger: ^2.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
